#ifndef  SCHEDULE_TABLE_H
#define SCHEDULE_TABLE_H

#define Version 1

#define CHANNEL_NUMBER 4

#define PUBLIC_BASE_ID 0x000

enum PUBLIC_FUNCTION
{
	CONTROL=0x001,
	CLOCK=0x002,
	READY=0x003
};

#define GIMALE_BASE_ID 0x010

enum GIMBAL_FUNCTION
{
	JUDGEMENT_17MM = 0x031,
	JUDGEMENT_BUFF =0x032,
};

#define CHASSIS_BASE_ID 0x030

enum CHASSIS_FUNCTION
{

};

#define SUPERC_BASE_ID 0x120

enum SUPERC_FUNCTION
{
	SUPERC_ON_TIME_POWER = 0x000,
	SUPERC_CAP_STATE = 0x001
};


enum IMU_BASE_ID
{
	IMU_1_ID = 0x131,
	IMU_2_ID = 0x132,
	IMU_3_ID = 0x133,
	IMU_4_ID = 0x134
};

enum IMU_FUNCTION
{
	IMU_ANGLE=0x000,
	IMU_ACC=0x010,
	IMU_ANGLE_SPEED=0x020
}; 

typedef struct
{
	int* channel_schedule_table;
	int table_length;
} channel_schedule_table_t;

int public_schedule_table_channel_[CHANNEL_NUMBER][] =
{ { SUPERC_BASE_ID + SUPERC_ON_TIME_POWER },
{ IMU_1_ID + IMU_ANGLE ,IMU_2_ID + IMU_ANGLE,IMU_3_ID+ IMU_ANGLE,,IMU_4_ID + IMU_ANGLE},
{IMU_1_ID + IMU_ANGLE_SPEED,IMU_2_ID + IMU_ANGLE_SPEED,IMU_3_ID + IMU_ANGLE_SPEED,IMU_4_ID + IMU_ANGLE_SPEED,
IMU_1_ID + IMU_ACC,IMU_2_ID + IMU_ACC,IMU_3_ID + IMU_ACC,IMU_4_ID + IMU_ACC},
{} };

#endif // ! SCHEDULE_TABLE_H

